### ISSUE TITLE
Can I use the latest BIOS version 210？

### ISSUE THREAD

**Issue by mxcos** [AlirezaH320/asus-n550jk-hackintosh#1]

**Comment by alirezatheh** [comment]
I haven't tested version `210`, but it should be ok. Make sure you are using correct [BIOS setting](https://github.com/AlirezaH320/asus-n550jk-hackintosh#bios-setting).

**Comment by mxcos** [comment]
I've tested it. If I start it directly, I will report an error. After I set the following three items to true, it's normal：

Config-Kernel-Quirks-AppleCpuPmCfgLock
Config-Kernel-Quirks-AppleXcpmCfgLock
Config-UEFI-Quirks-IgnoreInvalidFlexRatio

**Comment by mxcos** [comment]
Now I have another problem. Every time I turn on the built-in monitor, the screen will appear. I need to let the computer sleep first and then wake up. The display will be normal. Is there a solution to this problem?

**Comment by mxcos** [comment]
> Now I have another problem. Every time I turn on the built-in monitor, the screen will appear. I need to let the computer sleep first and then wake up. The display will be normal. Is there a solution to this problem?

I finally solved the problem of entering the system splash screen by adjusting the OC boot resolution. Adjust the OC resolution to 1024x768. Thanks for your job.

**Comment by alirezatheh** [comment]
> I've tested it. If I start it directly, I will report an error. After I set the following three items to true, it's normal：
> 
> Config-Kernel-Quirks-AppleCpuPmCfgLock
> Config-Kernel-Quirks-AppleXcpmCfgLock
> Config-UEFI-Quirks-IgnoreInvalidFlexRatio

These are temporary solutions. you should probably follow [this section](https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html) from [dortania](https://github.com/dortania)'s guide and disable CFG lock.

**Comment by alirezatheh** [comment]
> Now I have another problem. Every time I turn on the built-in monitor, the screen will appear. I need to let the computer sleep first and then wake up. The display will be normal. Is there a solution to this problem?

What do you mean "the screen will appear"?

**Comment by mxcos** [comment]
> > Now I have another problem. Every time I turn on the built-in monitor, the screen will appear. I need to let the computer sleep first and then wake up. The display will be normal. Is there a solution to this problem?
> 
> What do you mean "the screen will appear"?
![MalurT md](https://user-images.githubusercontent.com/17331141/112756318-30a99600-9017-11eb-8f3d-6becf46b4fea.jpg)
like this

**Comment by alirezatheh** [comment]
Did you disabled CSM?

**Comment by hackett0** [comment]
Not yet

I don't have windows anymore.

**Comment by mxcos** [comment]
> Did you disabled CSM?

Not yet

BIOS Ver 210:
`
OneOf Prompt: "CFG lock", Help: "Configure MSR 0xE2[15], CFG lock bit.", QuestionFlags: 0x10, QuestionId: 101, VarStoreId: 1, VarStoreOffset: 0x85, Flags: 0x10, MinMaxData: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	OneOfOption Option: "Disabled" Value: 0
	OneOfOption Option: "Enabled" Value: 1
End 
`
It looks the same as 208.

**Comment by alirezatheh** [comment]
> BIOS Ver 210:
> `OneOf Prompt: "CFG lock", Help: "Configure MSR 0xE2[15], CFG lock bit.", QuestionFlags: 0x10, QuestionId: 101, VarStoreId: 1, VarStoreOffset: 0x85, Flags: 0x10, MinMaxData: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] OneOfOption Option: "Disabled" Value: 0 OneOfOption Option: "Enabled" Value: 1 End `
> It looks the same as 208.

The screen problem is not related to CFG lock. I don't know If in version `210`, CSM is enabled by default or not. but make sure it is enabled. with default `CsmVideo`, boot resolution can not go further than `1024x768`, so either you have to deal with that or replace it with `HermitCsmVideo` to get full boot resolution.

**Comment by mxcos** [comment]
The "CFG lock" has been released.

[modGRUBShell.efi](https://github.com/datasone/grub-mod-setup_var/releases)

`GRUB> setup_var 0x85 0x00`

My current settings: 

`Config-Kernel-Quirks-AppleCpuPmCfgLock -> false`
`Config-Kernel-Quirks-AppleXcpmCfgLock -> false`
`Config-UEFI-Quirks-IgnoreInvalidFlexRatio -> true`

**Comment by mxcos** [comment]
Now there's a problem:
when I open `afuwin`  on my win10,
the system will crash.

I tried different versions of the afuwin, the result is still crash. 
I tried disable Intel Anti-Theft Technology , the result is still crash.

**Comment by alirezatheh** [comment]
It was ok on Windows 8.1 🤔.

**Comment by mxcos** [comment]
> It was ok on Windows 8.1 🤔.

still crash

**Comment by mxcos** [comment]
Which one should I use?

`Aptio V AMI Firmware Update Utility`
`Aptio 4 AMI Firmware Update Utility`
`AMIBIOS8 AMI Firmware Update Utility`

**Comment by alirezatheh** [comment]
> `Aptio V AMI Firmware Update Utility`

I used this one. Note that it will not work on a VM. are you using a real machine?

**Comment by mxcos** [comment]
I have tried Aptio V,Aptio 4,AMIBIOS8, 
in win8.1, win10, on the real machine,
it's all crash.

Finally, the problem is solved:
1. Make a dos usb boot disk used [Rufus v3.13 Portable.zip](https://github.com/AlirezaH320/asus-n550jk-hackintosh/files/6247240/Rufus.v3.13.Portable.zip).
2. Boot from usb dos.
3. Run the command used aptio 4:
`AFUDOS.EXE N550KJ.210.ROM`

[N550JK.210.zip](https://github.com/AlirezaH320/asus-n550jk-hackintosh/files/6247286/N550JK.210.zip)
note: N550JKAS.210 is downloaded from ASUS website, 
N550JK.210.rom is modified with UEFItools, and replace the CsmVideo body with HermitCsmVideo.fbd, finally exported whole body.

Now everything is well.
I got a higher boot resolution.
Thank you.

**Comment by alirezatheh** [comment]
So good to hear this. good lock. 👍

**Comment by nvmnghia** [comment]
I got to the same situation as @hackett0 , garbled/stripped screen, but the cursor is perfectly visible. @AlirezaTheH , could you share the source for the Hermit CSM BIOS patch? Mine is G551 Haswell, pretty close to this one.

**Comment by alirezatheh** [comment]
The [source](https://github.com/AlirezaTheH/asus-n550jk-hackintosh/blob/main/BIOS/HermitCsmVideo.fbd) is available in the BIOS folder.

**Comment by nvmnghia** [comment]
No, I mean the source of information, like HCL page, forum posts etc, so that I can do this patch for my machine. I havent found anything about them so far.

**Comment by alirezatheh** [comment]
Have you seen [this section](https://github.com/AlirezaTheH/asus-n550jk-hackintosh#bios-setting-1)?

**Comment by nvmnghia** [comment]
> > > Now I have another problem. Every time I turn on the built-in monitor, the screen will appear. I need to let the computer sleep first and then wake up. The display will be normal. Is there a solution to this problem?
> > 
> > 
> > What do you mean "the screen will appear"?
> > ![MalurT md](https://user-images.githubusercontent.com/17331141/112756318-30a99600-9017-11eb-8f3d-6becf46b4fea.jpg)
> > like this

Hi, I have a few question:

- Was the pointer perfectly visible at the screen? By "perfectly" I mean the pointer is not stripped at all.
- Could you share the exact step you did to fix the stripped screen?

Currently in my case:
  - Enable CSM: the laptop screen is completely blackout, the backlight isn't even on
  - Disable CSM: stripped screen like yours

Could you please help me? Thanks in advance.

@AlirezaTheH , I'm still reluctant at applying the Hermit patch :(. Hope you can help me with this.

Update: footage on the pointer situation:

![image](https://user-images.githubusercontent.com/22721156/149996697-6b9ca5e8-97e7-492d-ba0a-9431bbcf88e2.jpeg)
