### ISSUE TITLE
Support gtx850m

### ISSUE THREAD

**Issue by ProxVirtualZone** [AlirezaH320/asus-n550jk-hackintosh#20]
I’ve just found, that it’s possible to activate gtx850m in our notebook for hackintosh:
https://github.com/xCuri0/ReBarUEFI/issues/16#issuecomment-1452772245

And here’s a guide how to enable OpenGL acceleration for our gpu in Ventura: https://m.youtube.com/watch?v=QMhOeXMea8c

Maybe we can try it? I can help with modding bios if you need.

PS: I’ve already saw issue #12 and @5l1v3r1 had some progress since this issue with bypassing Optimus through minidisplayport.

**Comment by alirezatheh** [comment]
Hi,  yeah it's possible through mini display port but I'm not interested.
