### ISSUE TITLE
Can I also apply these EFI settings on N550JV?

### ISSUE THREAD

**Issue by DAIGOR1024** [AlirezaH320/asus-n550jk-hackintosh#3]
## Specifications
| **Component** | **Model** |
| ------------- | ------------- |
| CPU | i7  4700HQ  Processor |
| iGPU | HD 4600 |
| dGPU | NVIDIA GT 750M |
| RAM | 8 GB DDR3L 1600 MHz |
| STORAGE | PLEXTOR M6S |
| WLAN CHIPSET | BCM94352 |
| LAN CHIPSET | RTL8168 |
| BLUETOOTH | 4.0 |
| AUDIO CHIPSET | ALC668 |

Thanks~

**Comment by alirezatheh** [comment]
Yes, but you should create a CPUFriendDataProvider kext for your processor using [this guide](https://www.olarila.com/topic/5693-guide-ssdt-with-pikes-pm-script-and-use-with-cpufriend/).

**Comment by DAIGOR1024** [comment]
> Yes, but you should create a CPUFriendDataProvider kext for your processor using [this guide](https://www.olarila.com/topic/5693-guide-ssdt-with-pikes-pm-script-and-use-with-cpufriend/).

Thanks~
Will have a try

**Comment by DAIGOR1024** [comment]
Which mac os version you are using? 10.15.x or 11.x?

**Comment by alirezatheh** [comment]
`11.5.1`

**Comment by alirezatheh** [comment]
I noticed that your Wi-Fi card is different. So you also need to remove all Wi-Fi and Bluetooth kexts from Kexts folder and config.plist and add BCM kexts.

**Comment by DAIGOR1024** [comment]
> I noticed that your Wi-Fi card is different. So you also need to remove all Wi-Fi and Bluetooth kexts from Kexts folder and config.plist and add BCM kexts.

Yes, and also the dGPU part.

**Comment by alirezatheh** [comment]
> Yes, and also the dGPU part.

Yes, but it doesn't matter. Because it will not work and should be disabled to save power.

**Comment by DAIGOR1024** [comment]
> > Yes, and also the dGPU part.
> 
> Yes, but it doesn't matter. Because it will not work and should be disabled to save power.

**Comment by DAIGOR1024** [comment]
Seems the latest version of UEFITool can not replace the body for below step?
"iv. Search for `CsmVideo` and replace the body with [HermitCsmVideo.fbd](BIOS/HermitCsmVideo.fbd) and save."

**Comment by alirezatheh** [comment]
The latest version is an alpha release, use version `0.28.0`.
