### ISSUE TITLE
Realtek card kext

### ISSUE THREAD

**Issue by ProxVirtualZone** [AlirezaH320/asus-n550jk-hackintosh#4]
I don’t know why, but I can’t install Monterey with your RealtekRTL8111.kext… With your kext lan haven’t recognized. But I’ve found the solution. 

https://github.com/Mieze/RTL8111_driver_for_OS_X - this one is working normally for me

**Comment by alirezatheh** [comment]
@PeLLmEn Thank you for letting me know. Somehow I forgot to update the ethernet kext. I released a new version which will fix this.
